name: Build & Push Docker
on:
  pull_request:
    branches:
      - dev
      - main
    types:
      - closed
  workflow_dispatch:
jobs:
  build:
    if: github.event_name == 'workflow_dispatch' && github.actor == 'm-f-1998' || github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push Docker image
        run: |
            if [[ "${GITHUB_REF##*/}" == "dev" ]]; then
              ./docker/compile.sh dev
            else
              ./docker/compile.sh prod
            fi
