name: Build & Push Docker
on:
  push:
    branches:
      - dev
      - prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push Docker image
        run: |
            if [[ "${GITHUB_REF##*/}" == "dev" ]]; then
              ./docker/compile.sh dev
            else
              ./docker/compile.sh prod
            fi